### ISSUE TITLE
hx mac install - `hx update` does not work and `hyphen update` requires sudo

### ISSUE THREAD

**Issue by kylekampy** [Hyphen/hx#121]
problem 1: the install installs to a location that requires sudo.
problem 2: the update `hx update` requires sudo because of the install location. `sudo hx update` then fails because the `hx` alias is not in the profile for sudo. `sudo hyphen update` finally suceeds.

I think fixing problem 1 fixes problem 2 as well.

**Comment by Abraxas-365** [comment]
@kylekampy I think we can close this one right?

**Comment by kylekampy** [comment]
I think so - have we validated the fix?

**Comment by Abraxas-365** [comment]
Yesterday @cialese installed the CLI via the command, and she didn't use sudo. Also, when updating, she didn't need sudo.
