### ISSUE TITLE
Redirect authentication success page to hyphen.ai/cli?authenticated=true

### ISSUE THREAD

**Issue by nathanyoung** [Hyphen/hx#143]
https://hyphen.ai/cli?authenticated=true

**Comment by Abraxas-365** [comment]
@nathanyoung is the URL in the card correct ? Or should I use the one in the title ?

**Comment by nathanyoung** [comment]
@Abraxas-365 sorry, should be https://hyphen.ai/cli?authenticated=true

The one for `dev` is here: https://dev.hyphen.ai/cli?authenticated=true
